"""
AvatarService
=============
Player avatar upload — stored as files under app/static/uploads/avatars/,
served by Flask's normal static route. Kept separate from ProfileService:
file I/O and content sniffing are a different concern from the plain-field
profile edit (nickname/bio).

Validation is signature-based (magic bytes), not just extension — an
uploaded file claiming to be .png but containing something else is
rejected, since Flask's static handler would otherwise happily serve it
with an image/* content-type based on the extension alone.
"""
from __future__ import annotations

import os
import uuid
from typing import Optional

from flask import current_app
from werkzeug.datastructures import FileStorage

from app import db
from app.models import Player
from app.services.profile_service import ProfileResult

MAX_BYTES = 3 * 1024 * 1024  # 3 MB

# Allowed extension -> valid leading byte signature(s) for that format.
_SIGNATURES = {
    "png": [b"\x89PNG\r\n\x1a\n"],
    "jpg": [b"\xff\xd8\xff"],
    "jpeg": [b"\xff\xd8\xff"],
    "gif": [b"GIF87a", b"GIF89a"],
    "webp": [b"RIFF"],  # + bytes[8:12] == b"WEBP", checked separately below
}


class AvatarService:

    @staticmethod
    def _upload_dir() -> str:
        path = os.path.join(current_app.static_folder, "uploads", "avatars")
        os.makedirs(path, exist_ok=True)
        return path

    @staticmethod
    def _validate(filename: str, data: bytes) -> Optional[str]:
        """Returns a user-facing error message, or None if valid."""
        if not filename or "." not in filename:
            return "Не удалось определить формат файла."
        ext = filename.rsplit(".", 1)[1].lower()
        if ext not in _SIGNATURES:
            return "Разрешены только PNG, JPG, GIF или WEBP."
        if not data:
            return "Файл пустой."
        if len(data) > MAX_BYTES:
            return f"Файл слишком большой (максимум {MAX_BYTES // (1024 * 1024)} МБ)."
        if not any(data.startswith(sig) for sig in _SIGNATURES[ext]):
            return "Содержимое файла не похоже на изображение указанного формата."
        if ext == "webp" and data[8:12] != b"WEBP":
            return "Содержимое файла не похоже на изображение указанного формата."
        return None

    @staticmethod
    def _local_path(avatar_url: Optional[str]) -> Optional[str]:
        """
        Maps a stored "/static/uploads/avatars/<file>" URL back to an
        on-disk path — only for URLs generated by this service. Avatars
        set before this feature existed (arbitrary external URLs) are
        left alone, never deleted from disk.
        """
        prefix = "/static/uploads/avatars/"
        if not avatar_url or not avatar_url.startswith(prefix):
            return None
        filename = avatar_url[len(prefix):]
        if not filename or "/" in filename or ".." in filename:
            return None
        return os.path.join(AvatarService._upload_dir(), filename)

    @staticmethod
    def _safe_remove(path: str) -> None:
        try:
            if os.path.isfile(path):
                os.remove(path)
        except OSError:
            current_app.logger.warning("Could not remove old avatar file: %s", path)

    @staticmethod
    def save_avatar(player: Player, file: Optional[FileStorage]) -> ProfileResult:
        if not file or not file.filename:
            return ProfileResult.fail("Файл не выбран.")

        data = file.read()
        error = AvatarService._validate(file.filename, data)
        if error:
            return ProfileResult.fail(error)

        ext = file.filename.rsplit(".", 1)[1].lower()
        old_path = AvatarService._local_path(player.avatar_url)

        filename = f"{player.id}-{uuid.uuid4().hex[:12]}.{ext}"
        dest = os.path.join(AvatarService._upload_dir(), filename)
        with open(dest, "wb") as f:
            f.write(data)

        player.avatar_url = f"/static/uploads/avatars/{filename}"
        db.session.commit()

        if old_path:
            AvatarService._safe_remove(old_path)

        return ProfileResult.success("Аватар обновлён.", data=player.avatar_url)

    @staticmethod
    def remove_avatar(player: Player) -> ProfileResult:
        if not player.avatar_url:
            return ProfileResult.fail("Аватар не задан.")
        old_path = AvatarService._local_path(player.avatar_url)
        player.avatar_url = None
        db.session.commit()
        if old_path:
            AvatarService._safe_remove(old_path)
        return ProfileResult.success("Аватар удалён.")
